dist: xenial

os: linux

language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev  -t jvrh/docker-teste .

script:
  - docker run -e CI=true jvrh/docker-teste npm run test

    
