dist: xenial

os: linux

language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev  -t jvrh/docker-teste .

script:
  - docker run -e CI=true jvrh/docker-teste npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-teste"
  env: "DockerTeste-env"
  bucket_name: "elasticbeanstalk-sa-east-1-233123854740"
  bucket_path: "docker-teste"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
